// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl7wQeraCIGIDUjumpUYmF3M3VV4qBKf0',
    appId: '1:146261778283:web:697653eb84e4ac3061f62e',
    messagingSenderId: '146261778283',
    projectId: 'login-page-fd716',
    authDomain: 'login-page-fd716.firebaseapp.com',
    storageBucket: 'login-page-fd716.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9fWAAFRWHCQbJqUjJwtqsgJ5yjnbIEc',
    appId: '1:146261778283:android:0a443f5b6765bd1c61f62e',
    messagingSenderId: '146261778283',
    projectId: 'login-page-fd716',
    storageBucket: 'login-page-fd716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh6EZVt9L-xyrurSxfxaCevxleSOC-kjs',
    appId: '1:146261778283:ios:f1e368251e793bcc61f62e',
    messagingSenderId: '146261778283',
    projectId: 'login-page-fd716',
    storageBucket: 'login-page-fd716.appspot.com',
    iosClientId: '146261778283-o87308jflflfh3783snjjl49ab8qsjbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
